baseURL = 'https://brandontaylor.tech/'
languageCode = 'en-us'
title = 'BrandonTaylor.tech'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
copyright = 'Brandon Taylor'
[params]
    show_reading_time = true
    site_logo = "/images/site_logo_white.png"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/bmt626"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/bmt626"

[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/bmtaylor"

[[params.ananke_socials]]
name = "mastodon"
rel = "me"
url = "https://infosec.exchange/@bmt626"
